#!/bin/bash

echo ""
echo "┌─────────────────────────────────────────────────────┐"
echo "│             BookMyTime Development Dashboard        │"
echo "├─────────────────────────────────────────────────────┤"
echo "│  Status: 🟢 FULL STACK READY                        │"
echo "│  Date:   $(date)                                   │"
echo "└─────────────────────────────────────────────────────┘"
echo ""
echo "🌐 SERVICES:"
echo "  Frontend:    http://localhost:5173"
echo "  Backend API: http://localhost:8080"
echo "  PostgreSQL:  localhost:5432"
echo "  OpenSearch:  http://localhost:9200"
echo ""
echo "🔗 API ENDPOINTS:"
echo "  Health:      http://localhost:8080/api/health"
echo "  DB Health:   http://localhost:8080/api/database/health"
echo "  DB Test:     http://localhost:8080/api/database/test"
echo "  Actuator:    http://localhost:8080/actuator"
echo ""
echo "📊 TEST COMMANDS:"
echo "  Test backend:    curl http://localhost:8080/api/health"
echo "  Test proxy:      curl http://localhost:5173/api/health"
echo "  Test database:   curl http://localhost:8080/api/database/health"
echo ""
echo "🛠️  DEVELOPMENT:"
echo "  Frontend dir:    apps/web/"
echo "  Backend dir:     apps/api/"
echo "  Infra config:    infrastructure/"
echo ""
echo "📝 NEXT STEPS:"
echo "  1. Design database schema for users/providers"
echo "  2. Create JPA entities"
echo "  3. Implement authentication"
echo "  4. Build React components"
echo ""
